---

- name: Install Wordpress DB
  hosts: db
  become: yes
  become_user: root
  roles:
  - wordpress-db

- name: Install Wordpress Web
  hosts: web
  become: yes
  become_user: root
  roles:
  - wordpress-app

- name: Install CDN server
  hosts: cdn
  become: yes
  become_user: root
  roles:
  - cdn-server
