---

- name: Install packages
  apt: name=nginx state=present

- name: Enable services
  service: name=nginx enabled=yes

- name: Copy index html file
  template: src=index.html dest=/usr/share/nginx/html/

- name: Get cat
  get_url: 
    url: "https://upload.wikimedia.org/wikipedia/commons/8/83/Neugierige-Katze.JPG"
    dest: /usr/share/nginx/html/cat.jpg
    checksum: "sha256:a32c38ceee2959db5adf339d598262db911d25f7a391df3974f8f7d7cf11efc4"


